[2022-02-21T14:00:59.696] [ERROR] ma-core - "timeZone" is required /api/itoperation/getAllActive POST ::1
[2022-02-21T14:24:13.777] [ERROR] ma-core - formValidator in insert resultform validation : gStatus | taskId undefined testing testing testing
[2022-02-21T14:24:13.783] [ERROR] ma-core - formValidator in insert resultform validation : gStatus | taskId undefined testing testing testing
[2022-02-21T14:24:13.784] [ERROR] ma-core - formValidator in insert resultform validation : gStatus | taskId undefined testing testing testing
[2022-02-21T14:26:09.008] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:26:09.010] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:26:09.060] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:26:09.077] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:26:09.092] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:26:09.027] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:26:09.028] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:26:09.108] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:30:30.824] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:30:30.827] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:30:30.889] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:30:30.908] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:30:30.923] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:30:30.844] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:30:30.845] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:30:30.941] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:31:56.683] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:31:56.686] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:31:56.748] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:31:56.767] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:31:56.781] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:31:56.702] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:31:56.704] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:31:56.800] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:33:31.423] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:33:31.426] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:33:31.480] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:33:31.496] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:33:31.516] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:33:31.445] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:33:31.447] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:33:31.533] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:36:52.077] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:36:52.079] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:36:52.143] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:36:52.162] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:36:52.177] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:36:52.095] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:36:52.097] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:36:52.195] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:39:25.226] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:39:25.228] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:39:25.294] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:39:25.316] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:39:25.331] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:39:25.245] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:39:25.246] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:39:25.349] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:50:25.866] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:50:25.868] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:50:25.929] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:50:25.953] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:50:25.968] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:50:25.884] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:50:25.885] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:50:25.986] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:51:18.296] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:51:18.298] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:51:18.346] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:51:18.366] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:51:18.381] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:51:18.314] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:51:18.316] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:51:18.398] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T14:54:11.390] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T14:54:11.393] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T14:54:11.452] [ERROR] ma-core - get All Active ItOperation :undefined testing testing testing
[2022-02-21T14:54:11.467] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T14:54:11.483] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T14:54:11.408] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T14:54:11.410] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T14:54:11.499] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T15:57:07.186] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T15:57:07.204] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-02-21T16:15:19.322] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:26:40.038] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:27:53.292] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:35:17.216] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:35:55.682] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:36:33.707] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:39:15.742] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:40:35.991] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:45:05.336] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:47:01.802] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:47:59.110] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:48:54.125] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:49:51.358] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:51:56.586] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:53:09.153] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:54:13.916] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:55:51.948] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:57:32.846] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:58:06.700] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:58:46.176] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:58:59.415] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T16:59:50.407] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:00:03.460] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:00:18.438] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:00:33.422] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:00:48.004] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:01:15.936] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:02:18.435] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:04:43.927] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:04:43.943] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:04:43.945] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:05:26.783] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:05:26.799] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:05:26.801] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:06:00.036] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:06:00.050] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:06:00.051] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:06:47.209] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:06:47.223] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:06:47.225] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:14:01.825] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:14:01.839] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:14:01.841] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:14:12.353] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:14:12.368] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:14:12.370] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:27:10.680] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:27:10.696] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:27:10.698] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:28:20.323] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:28:20.338] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:28:20.340] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:29:13.596] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:29:13.615] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:29:13.617] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:32:01.387] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:32:01.402] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:32:01.404] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T17:33:44.955] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T17:33:44.970] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T17:33:44.972] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T18:48:30.430] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T18:48:30.445] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T18:48:30.447] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T18:50:59.494] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-21T18:50:59.496] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-21T18:50:59.506] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.507] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.531] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllClientBySystemServiceTest.js:58:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.538] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.562] [ERROR] ma-core - Error while sending comment notification TypeError: Cannot read property 'split' of undefined
    at Object.build (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/connectionBuilder.js:60:29)
    at async BrokerPool.createSeedBroker (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/brokerPool.js:70:19)
    at async BrokerPool.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/brokerPool.js:85:7)
    at async Cluster.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/index.js:109:5)
    at async Object.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/producer/index.js:223:7)
    at async Object.exports.commentNotif (/home/azer/avaxia-monitpring-app/core-service/kafka/notificationServiceKafka.js:2:3972)
    at async module.exports (/home/azer/avaxia-monitpring-app/core-service/services/comment/blockComment.service.js:2:724)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/comment/block/blockComment.service.test.js:34:17)
[2022-02-21T18:50:59.633] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.653] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-02-21T18:50:59.761] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.770] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:59:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.777] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.782] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-02-21T18:50:59.791] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:57.005] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T18:50:57.006] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T18:50:59.814] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.823] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T18:50:57.018] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T18:50:57.020] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T18:50:59.840] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T18:50:59.876] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-02-21T18:50:59.877] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-02-21T18:50:59.888] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-02-21T18:50:59.890] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-02-21T18:50:59.892] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-21T18:50:59.893] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-21T18:50:59.897] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.900] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:50:59.906] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-21T18:50:59.908] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-21T18:50:59.919] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-02-21T18:50:59.920] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-02-21T18:50:59.933] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-02-21T18:50:59.934] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-02-21T18:50:59.948] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-02-21T18:50:59.951] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-21T18:50:59.952] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-21T18:50:59.953] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-02-21T18:50:59.974] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-02-21T18:50:59.977] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:51:00.004] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-02-21T18:51:00.005] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-02-21T18:51:00.007] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-21T18:51:00.009] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-21T18:51:00.017] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-02-21T18:51:00.018] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-02-21T18:51:00.024] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-02-21T18:51:00.026] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-02-21T18:51:00.034] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-21T18:51:00.035] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-21T18:51:00.037] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-02-21T18:51:00.047] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-02-21T18:51:00.049] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-02-21T18:51:00.062] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-21T18:51:00.063] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-21T18:51:00.066] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-02-21T18:51:00.137] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T18:51:00.151] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T18:51:00.153] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T18:51:00.162] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-02-21T18:51:00.165] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-02-21T18:51:00.191] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-02-21T18:51:00.192] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-02-21T18:51:00.209] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-02-21T18:51:00.212] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-02-21T18:51:00.219] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-02-21T18:51:00.221] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-02-21T18:51:00.228] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error testing testing testing
[2022-02-21T18:51:00.230] [ERROR] ma-core - get Monitoring Activities Without Result Forms :not found error testing testing testing
[2022-02-21T18:51:00.231] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error NaN post 1234
[2022-02-21T18:51:00.240] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-02-21T18:51:00.248] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-02-21T18:51:00.254] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-02-21T18:51:00.255] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-02-21T18:51:00.264] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-02-21T18:51:00.265] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-02-21T18:51:00.266] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-21T18:51:00.267] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-21T18:51:00.278] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-02-21T18:51:00.280] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-02-21T18:51:00.286] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-21T18:51:00.287] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-21T18:51:00.290] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-02-21T18:51:00.301] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-02-21T18:51:00.302] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-02-21T18:51:00.305] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-02-21T18:51:00.308] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-02-21T18:51:00.310] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-02-21T18:51:00.322] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-21T18:51:00.323] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-21T18:51:00.325] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-02-21T18:51:00.341] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-21T18:51:00.342] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-21T18:51:00.371] [ERROR] ma-core - 
[2022-02-21T18:51:00.446] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-21T18:51:00.447] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-21T18:51:00.452] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-02-21T18:51:00.462] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-21T18:51:00.464] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-21T18:51:00.466] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-02-21T18:51:00.472] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:51:00.481] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-02-21T18:51:00.483] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-02-21T18:51:00.500] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-21T18:51:00.501] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-21T18:51:00.503] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-02-21T18:51:00.512] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-02-21T18:51:00.513] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-02-21T18:51:00.525] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:51:00.531] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-02-21T18:51:00.532] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-02-21T18:51:00.536] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-02-21T18:51:00.537] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-02-21T18:51:00.548] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-02-21T18:51:00.549] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-02-21T18:51:00.561] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-02-21T18:51:00.563] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-02-21T18:51:00.730] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:51:00.760] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:51:00.792] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:51:00.814] [ERROR] ma-core - get All Task :an error occured testing testing testing
[2022-02-21T18:51:00.816] [ERROR] ma-core - get All Task :an error occured NaN post 1234
[2022-02-21T18:51:00.822] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-21T18:51:00.831] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-21T18:51:00.836] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-21T18:51:00.838] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-02-21T18:51:00.846] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-21T18:51:00.959] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-02-21T18:51:00.964] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-02-21T18:51:01.042] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-02-21T18:51:01.044] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-02-21T18:51:01.060] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-02-21T18:51:01.061] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-02-21T18:51:01.072] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-02-21T18:51:01.073] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-21T18:51:01.083] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-02-21T18:51:01.105] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-02-21T18:51:01.107] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-02-21T18:51:01.117] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-21T18:51:01.120] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-21T18:51:01.130] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-02-21T18:51:01.132] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-02-21T18:51:01.140] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-02-21T18:51:01.141] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-02-21T18:51:01.153] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-21T18:51:01.154] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-21T18:51:01.157] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-02-21T18:51:01.160] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-02-21T18:51:01.165] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-02-21T18:51:01.165] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-02-21T18:51:01.167] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-02-21T18:51:01.168] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-02-21T18:51:01.178] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-02-21T18:51:01.182] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-21T18:51:01.258] [ERROR] ma-core - random Error
[2022-02-21T18:51:01.923] [ERROR] ma-core - random error
[2022-02-21T18:53:10.365] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-21T18:53:10.367] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-21T18:53:10.378] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.379] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.407] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllClientBySystemServiceTest.js:58:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.414] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.433] [ERROR] ma-core - Error while sending comment notification TypeError: Cannot read property 'split' of undefined
    at Object.build (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/connectionBuilder.js:60:29)
    at async BrokerPool.createSeedBroker (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/brokerPool.js:70:19)
    at async BrokerPool.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/brokerPool.js:85:7)
    at async Cluster.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/index.js:109:5)
    at async Object.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/producer/index.js:223:7)
    at async Object.exports.commentNotif (/home/azer/avaxia-monitpring-app/core-service/kafka/notificationServiceKafka.js:2:3972)
    at async module.exports (/home/azer/avaxia-monitpring-app/core-service/services/comment/blockComment.service.js:2:724)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/comment/block/blockComment.service.test.js:34:17)
[2022-02-21T18:53:10.509] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.525] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-02-21T18:53:10.630] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.637] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:59:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.644] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.651] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-02-21T18:53:10.660] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:08.687] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T18:53:08.689] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T18:53:10.682] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.695] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T18:53:08.703] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T18:53:08.705] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T18:53:10.711] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T18:53:10.742] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-02-21T18:53:10.743] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-02-21T18:53:10.759] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-02-21T18:53:10.761] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-02-21T18:53:10.763] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-21T18:53:10.765] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-21T18:53:10.769] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.773] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.781] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-21T18:53:10.782] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-21T18:53:10.793] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-02-21T18:53:10.795] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-02-21T18:53:10.814] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-02-21T18:53:10.815] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-02-21T18:53:10.830] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-02-21T18:53:10.833] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-21T18:53:10.834] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-21T18:53:10.836] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-02-21T18:53:10.854] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-02-21T18:53:10.858] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:10.886] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-02-21T18:53:10.888] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-02-21T18:53:10.890] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-21T18:53:10.891] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-21T18:53:10.900] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-02-21T18:53:10.902] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-02-21T18:53:10.915] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-02-21T18:53:10.920] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-02-21T18:53:10.950] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-21T18:53:10.952] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-21T18:53:10.955] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-02-21T18:53:10.967] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-02-21T18:53:10.968] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-02-21T18:53:10.976] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-21T18:53:10.978] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-21T18:53:10.980] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-02-21T18:53:11.053] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T18:53:11.068] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T18:53:11.070] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T18:53:11.080] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-02-21T18:53:11.083] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-02-21T18:53:11.109] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-02-21T18:53:11.110] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-02-21T18:53:11.127] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-02-21T18:53:11.129] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-02-21T18:53:11.137] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-02-21T18:53:11.139] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-02-21T18:53:11.147] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error testing testing testing
[2022-02-21T18:53:11.149] [ERROR] ma-core - get Monitoring Activities Without Result Forms :not found error testing testing testing
[2022-02-21T18:53:11.150] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error NaN post 1234
[2022-02-21T18:53:11.162] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-02-21T18:53:11.163] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-02-21T18:53:11.169] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-02-21T18:53:11.170] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-02-21T18:53:11.179] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-02-21T18:53:11.180] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-02-21T18:53:11.181] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-21T18:53:11.183] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-21T18:53:11.193] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-02-21T18:53:11.195] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-02-21T18:53:11.201] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-21T18:53:11.202] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-21T18:53:11.204] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-02-21T18:53:11.215] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-02-21T18:53:11.216] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-02-21T18:53:11.218] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-02-21T18:53:11.222] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-02-21T18:53:11.224] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-02-21T18:53:11.236] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-21T18:53:11.237] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-21T18:53:11.239] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-02-21T18:53:11.252] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-21T18:53:11.253] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-21T18:53:11.281] [ERROR] ma-core - 
[2022-02-21T18:53:11.365] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-21T18:53:11.366] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-21T18:53:11.368] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-02-21T18:53:11.377] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-21T18:53:11.380] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-21T18:53:11.381] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-02-21T18:53:11.388] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:11.397] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-02-21T18:53:11.399] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-02-21T18:53:11.415] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-21T18:53:11.417] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-21T18:53:11.418] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-02-21T18:53:11.427] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-02-21T18:53:11.428] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-02-21T18:53:11.440] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:11.445] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-02-21T18:53:11.446] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-02-21T18:53:11.453] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-02-21T18:53:11.454] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-02-21T18:53:11.462] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-02-21T18:53:11.463] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-02-21T18:53:11.474] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-02-21T18:53:11.476] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-02-21T18:53:11.662] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:11.687] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:11.721] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T18:53:11.741] [ERROR] ma-core - get All Task :an error occured testing testing testing
[2022-02-21T18:53:11.745] [ERROR] ma-core - get All Task :an error occured NaN post 1234
[2022-02-21T18:53:11.751] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-21T18:53:11.766] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-21T18:53:11.771] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-21T18:53:11.773] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-02-21T18:53:11.780] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-21T18:53:11.899] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-02-21T18:53:11.906] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-02-21T18:53:11.980] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-02-21T18:53:11.982] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-02-21T18:53:11.996] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-02-21T18:53:11.997] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-02-21T18:53:12.010] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-02-21T18:53:12.012] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-21T18:53:12.027] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-02-21T18:53:12.044] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-02-21T18:53:12.046] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-02-21T18:53:12.054] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-21T18:53:12.056] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-21T18:53:12.064] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-02-21T18:53:12.066] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-02-21T18:53:12.075] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-02-21T18:53:12.076] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-02-21T18:53:12.084] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-21T18:53:12.086] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-21T18:53:12.089] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-02-21T18:53:12.093] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-02-21T18:53:12.100] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-02-21T18:53:12.101] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-02-21T18:53:12.104] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-02-21T18:53:12.104] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-02-21T18:53:12.115] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-02-21T18:53:12.118] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-21T18:53:12.200] [ERROR] ma-core - random Error
[2022-02-21T18:53:12.878] [ERROR] ma-core - random error
[2022-02-21T19:01:10.427] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-21T19:01:10.428] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-21T19:01:10.439] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.441] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.466] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllClientBySystemServiceTest.js:58:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.473] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.490] [ERROR] ma-core - Error while sending comment notification TypeError: Cannot read property 'split' of undefined
    at Object.build (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/connectionBuilder.js:60:29)
    at async BrokerPool.createSeedBroker (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/brokerPool.js:70:19)
    at async BrokerPool.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/brokerPool.js:85:7)
    at async Cluster.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/cluster/index.js:109:5)
    at async Object.connect (/home/azer/avaxia-monitpring-app/core-service/node_modules/kafkajs/src/producer/index.js:223:7)
    at async Object.exports.commentNotif (/home/azer/avaxia-monitpring-app/core-service/kafka/notificationServiceKafka.js:2:3972)
    at async module.exports (/home/azer/avaxia-monitpring-app/core-service/services/comment/blockComment.service.js:2:724)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/comment/block/blockComment.service.test.js:34:17)
[2022-02-21T19:01:10.562] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.576] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2022-02-21T19:01:10.678] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.686] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:59:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.692] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.698] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2022-02-21T19:01:10.706] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:08.863] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2022-02-21T19:01:08.864] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2022-02-21T19:01:10.728] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.740] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2022-02-21T19:01:08.877] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2022-02-21T19:01:08.879] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2022-02-21T19:01:10.770] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2022-02-21T19:01:10.802] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2022-02-21T19:01:10.804] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2022-02-21T19:01:10.817] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2022-02-21T19:01:10.818] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2022-02-21T19:01:10.819] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-21T19:01:10.820] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-21T19:01:10.823] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.827] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.832] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2022-02-21T19:01:10.834] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2022-02-21T19:01:10.846] [ERROR] ma-core - add Licence :missing property testing testing testing
[2022-02-21T19:01:10.848] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2022-02-21T19:01:10.860] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2022-02-21T19:01:10.861] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2022-02-21T19:01:10.880] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2022-02-21T19:01:10.883] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-21T19:01:10.884] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2022-02-21T19:01:10.885] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2022-02-21T19:01:10.901] [ERROR] ma-core - Get by System Error : TypeError: moment(...).tz(...).format is not a function
    at /home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1950
    at Array.map (<anonymous>)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/map/getBySystemId.js:2:1771)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:71:17)
[2022-02-21T19:01:10.905] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:98:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:10.932] [ERROR] ma-core - delete Module :module not found testing testing testing
[2022-02-21T19:01:10.933] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2022-02-21T19:01:10.936] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-21T19:01:10.938] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2022-02-21T19:01:10.947] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2022-02-21T19:01:10.948] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2022-02-21T19:01:10.953] [ERROR] ma-core - get All Module :missing property testing testing testing
[2022-02-21T19:01:10.955] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2022-02-21T19:01:10.979] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-21T19:01:10.982] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2022-02-21T19:01:10.987] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2022-02-21T19:01:11.011] [ERROR] ma-core - add Module :missing property testing testing testing
[2022-02-21T19:01:11.013] [ERROR] ma-core - add Module :missing property NaN post 1234
[2022-02-21T19:01:11.020] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-21T19:01:11.022] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2022-02-21T19:01:11.024] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2022-02-21T19:01:11.096] [ERROR] ma-core - add post :missing property testing testing testing
[2022-02-21T19:01:11.105] [ERROR] ma-core - get All posts :An error message testing testing testing
[2022-02-21T19:01:11.106] [ERROR] ma-core - get All posts :An error message NaN post 1234
[2022-02-21T19:01:11.119] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2022-02-21T19:01:11.122] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2022-02-21T19:01:11.150] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2022-02-21T19:01:11.151] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2022-02-21T19:01:11.166] [ERROR] ma-core - get All result form :missing property testing testing testing
[2022-02-21T19:01:11.169] [ERROR] ma-core - get All result form :missing property NaN post 1234
[2022-02-21T19:01:11.175] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2022-02-21T19:01:11.177] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2022-02-21T19:01:11.184] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error testing testing testing
[2022-02-21T19:01:11.186] [ERROR] ma-core - get Monitoring Activities Without Result Forms :not found error testing testing testing
[2022-02-21T19:01:11.187] [ERROR] ma-core - get Monitoring Activities Without Result Forms :error NaN post 1234
[2022-02-21T19:01:11.194] [ERROR] ma-core - add result form :missing property testing testing testing
[2022-02-21T19:01:11.198] [ERROR] ma-core - add result form :missing property NaN post 1234
[2022-02-21T19:01:11.205] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2022-02-21T19:01:11.206] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2022-02-21T19:01:11.214] [ERROR] ma-core - delete Role :role not found testing testing testing
[2022-02-21T19:01:11.215] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2022-02-21T19:01:11.217] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-21T19:01:11.218] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2022-02-21T19:01:11.228] [ERROR] ma-core - get All Role :missing property testing testing testing
[2022-02-21T19:01:11.230] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2022-02-21T19:01:11.235] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-21T19:01:11.237] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2022-02-21T19:01:11.239] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2022-02-21T19:01:11.251] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2022-02-21T19:01:11.252] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2022-02-21T19:01:11.254] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2022-02-21T19:01:11.257] [ERROR] ma-core - add Role :missing property testing testing testing
[2022-02-21T19:01:11.259] [ERROR] ma-core - add Role :missing property NaN post 1234
[2022-02-21T19:01:11.270] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-21T19:01:11.271] [ERROR] ma-core - update Role :role not found testing testing testing
[2022-02-21T19:01:11.274] [ERROR] ma-core - update Role :role not found NaN post 1234
[2022-02-21T19:01:11.288] [ERROR] ma-core - add Client :missing property testing testing testing
[2022-02-21T19:01:11.290] [ERROR] ma-core - add Client :missing property NaN post 1234
[2022-02-21T19:01:11.317] [ERROR] ma-core - 
[2022-02-21T19:01:11.392] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-21T19:01:11.393] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2022-02-21T19:01:11.398] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2022-02-21T19:01:11.407] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-21T19:01:11.409] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2022-02-21T19:01:11.410] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2022-02-21T19:01:11.417] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:11.426] [ERROR] ma-core - add Sla :missing property testing testing testing
[2022-02-21T19:01:11.428] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2022-02-21T19:01:11.445] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-21T19:01:11.446] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2022-02-21T19:01:11.447] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2022-02-21T19:01:11.456] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2022-02-21T19:01:11.457] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2022-02-21T19:01:11.468] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:78:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:11.473] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2022-02-21T19:01:11.475] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2022-02-21T19:01:11.479] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2022-02-21T19:01:11.480] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2022-02-21T19:01:11.491] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2022-02-21T19:01:11.492] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2022-02-21T19:01:11.503] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2022-02-21T19:01:11.505] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2022-02-21T19:01:11.666] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:11.690] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:11.721] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:681:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:804:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:596:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:606:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:489:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:554:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:513:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:574:5)
    at processImmediate (internal/timers.js:464:21)
[2022-02-21T19:01:11.738] [ERROR] ma-core - get All Task :an error occured testing testing testing
[2022-02-21T19:01:11.740] [ERROR] ma-core - get All Task :an error occured NaN post 1234
[2022-02-21T19:01:11.745] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-21T19:01:11.754] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-21T19:01:11.758] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2022-02-21T19:01:11.763] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2022-02-21T19:01:11.770] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2022-02-21T19:01:11.885] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2022-02-21T19:01:11.889] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2022-02-21T19:01:11.948] [ERROR] ma-core - add Task :missing property testing testing testing
[2022-02-21T19:01:11.950] [ERROR] ma-core - add Task :missing property NaN post 1234
[2022-02-21T19:01:11.965] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2022-02-21T19:01:11.967] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2022-02-21T19:01:11.977] [ERROR] ma-core - update Task :task not found testing testing testing
[2022-02-21T19:01:11.978] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-21T19:01:11.988] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2022-02-21T19:01:12.009] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2022-02-21T19:01:12.010] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2022-02-21T19:01:12.018] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-21T19:01:12.020] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-21T19:01:12.027] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2022-02-21T19:01:12.029] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2022-02-21T19:01:12.037] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2022-02-21T19:01:12.038] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2022-02-21T19:01:12.046] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2022-02-21T19:01:12.048] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2022-02-21T19:01:12.051] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:51:5)
[2022-02-21T19:01:12.054] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:95:5)
[2022-02-21T19:01:12.059] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:176:5)
[2022-02-21T19:01:12.059] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2022-02-21T19:01:12.062] [ERROR] ma-core - An unexpected error occurred during auto start task Error: WARNING: Date in past. Will never be fired.
    at CronTime.sendAt (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:148:12)
    at CronTime.getTimeout (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:175:29)
    at CronJob.start (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:613:31)
    at new CronJob (/home/azer/avaxia-monitpring-app/core-service/node_modules/cron/lib/cron.js:576:10)
    at module.exports (/home/azer/avaxia-monitpring-app/core-service/services/task/autoStartTaskCron.js:2:1041)
    at Object.exports.validateTask (/home/azer/avaxia-monitpring-app/core-service/controllers/task.controller.js:11:699)
    at async Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/task/updateState/validateTask.controller.test.js:219:5)
[2022-02-21T19:01:12.062] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2022-02-21T19:01:12.073] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2022-02-21T19:01:12.076] [ERROR] ma-core - update Task :task not found NaN post 1234
[2022-02-21T19:01:12.145] [ERROR] ma-core - random Error
[2022-02-21T19:01:12.803] [ERROR] ma-core - random error
