[2021-12-06T09:03:57.971] [ERROR] ma-core - add Client :missing property testing testing testing
[2021-12-06T09:03:57.973] [ERROR] ma-core - add Client :missing property NaN post 1234
[2021-12-06T09:03:57.984] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:62:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:57.985] [ERROR] ma-core - Delete Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/delete/deleteClient.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.011] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/getClientsBySystemId/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.019] [ERROR] ma-core - Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/client/update/updateClient.service.test.js:70:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.049] [ERROR] ma-core - Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/customer/getById/getByIdCustomer.service.test.js:88:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.053] [ERROR] ma-core - add customer fail :missing property testing testing testing
[2021-12-06T09:03:58.154] [ERROR] ma-core - Delete Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/delete/deleteHost.service.test.js:72:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.161] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getAllBySystem/getAllBySystemServiceTest.js:49:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.168] [ERROR] ma-core - Get by ID Error : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/getById/getByIdHost.service.test.js:58:24)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.174] [ERROR] ma-core - expected findOneAndUpdate to have been called exactly once, but it was called 0 times
[2021-12-06T09:03:58.182] [ERROR] ma-core - Update Error : Error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/host/update/updateHost.service.test.js:79:33)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:54.637] [ERROR] ma-core - cancel ItOperation :itOperation not found testing testing testing
[2021-12-06T09:03:54.638] [ERROR] ma-core - finish ItOperation :itOperation not found testing testing testing
[2021-12-06T09:03:58.206] [ERROR] ma-core - Error occur while Getting ItOperation By System Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/itOperation/getAllBySystem/getAllBySystemServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.218] [ERROR] ma-core - add ItOperation fail :missing property testing testing testing
[2021-12-06T09:03:54.651] [ERROR] ma-core - remind ItOperation :itOperation not found testing testing testing
[2021-12-06T09:03:54.652] [ERROR] ma-core - send changes ItOperation :itOperation not found testing testing testing
[2021-12-06T09:03:58.233] [ERROR] ma-core - update ItOperation :itOperation not found testing testing testing
[2021-12-06T09:03:58.261] [ERROR] ma-core - delete Licence :licence not found testing testing testing
[2021-12-06T09:03:58.262] [ERROR] ma-core - delete Licence :licence not found NaN post 1234
[2021-12-06T09:03:58.271] [ERROR] ma-core - get licence By Id :Missing Customer ID NaN post 1234
[2021-12-06T09:03:58.272] [ERROR] ma-core - get licence By Id :Missing Customer ID testing testing testing
[2021-12-06T09:03:58.273] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2021-12-06T09:03:58.275] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2021-12-06T09:03:58.278] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getActiveLicence/getActiveLIcenceServiceTest.js:52:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.281] [ERROR] ma-core - Error occur while Getting Licence By Customer Id : Error: random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/licence/getByCustomer/getByCustomerLicence.service.test.js:61:17)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.289] [ERROR] ma-core - get licence By Id :licence not found testing testing testing
[2021-12-06T09:03:58.290] [ERROR] ma-core - get licence By Id :licence not found NaN post 1234
[2021-12-06T09:03:58.300] [ERROR] ma-core - add Licence :missing property testing testing testing
[2021-12-06T09:03:58.302] [ERROR] ma-core - add Licence :missing property NaN post 1234
[2021-12-06T09:03:58.317] [ERROR] ma-core - update licence By Customer :licence not found testing testing testing
[2021-12-06T09:03:58.319] [ERROR] ma-core - update licence By Customer :licence not found NaN post 1234
[2021-12-06T09:03:58.334] [ERROR] ma-core - delete Map By Id :MAP not found testing testing testing
[2021-12-06T09:03:58.338] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2021-12-06T09:03:58.339] [ERROR] ma-core - delete Map By Id :missing ID testing testing testing
[2021-12-06T09:03:58.340] [ERROR] ma-core - delete Map By Id :missing ID NaN post 1234
[2021-12-06T09:03:58.361] [ERROR] ma-core - Get by System Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/map/getAllBySystem/getAllBySystemServiceTest.js:52:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.389] [ERROR] ma-core - delete Module :module not found testing testing testing
[2021-12-06T09:03:58.391] [ERROR] ma-core - delete Module :module not found NaN post 1234
[2021-12-06T09:03:58.393] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2021-12-06T09:03:58.394] [ERROR] ma-core - delete Module :missing ID testing testing testing
[2021-12-06T09:03:58.403] [ERROR] ma-core - get All Basic Module :missing property testing testing testing
[2021-12-06T09:03:58.407] [ERROR] ma-core - get All Basic Module :missing property NaN post 1234
[2021-12-06T09:03:58.414] [ERROR] ma-core - get All Module :missing property testing testing testing
[2021-12-06T09:03:58.416] [ERROR] ma-core - get All Module :missing property NaN post 1234
[2021-12-06T09:03:58.423] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2021-12-06T09:03:58.425] [ERROR] ma-core - get module By Id :module not found testing testing testing
[2021-12-06T09:03:58.427] [ERROR] ma-core - get module By Id :module not found NaN post 1234
[2021-12-06T09:03:58.438] [ERROR] ma-core - add Module :missing property testing testing testing
[2021-12-06T09:03:58.439] [ERROR] ma-core - add Module :missing property NaN post 1234
[2021-12-06T09:03:58.449] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2021-12-06T09:03:58.450] [ERROR] ma-core - update module By Customer :module not found testing testing testing
[2021-12-06T09:03:58.452] [ERROR] ma-core - update module By Customer :module not found NaN post 1234
[2021-12-06T09:03:58.528] [ERROR] ma-core - get All nomenclature :get All nomenclature : testing testing testing
[2021-12-06T09:03:58.529] [ERROR] ma-core - get All nomenclature :get All nomenclature : NaN post 1234
[2021-12-06T09:03:58.578] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2021-12-06T09:03:58.579] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2021-12-06T09:03:58.594] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2021-12-06T09:03:58.596] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2021-12-06T09:03:58.605] [ERROR] ma-core - add result form :missing property testing testing testing
[2021-12-06T09:03:58.606] [ERROR] ma-core - add result form :missing property NaN post 1234
[2021-12-06T09:03:58.613] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2021-12-06T09:03:58.614] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
[2021-12-06T09:03:58.624] [ERROR] ma-core - delete Role :role not found testing testing testing
[2021-12-06T09:03:58.626] [ERROR] ma-core - delete Role :role not found NaN post 1234
[2021-12-06T09:03:58.627] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2021-12-06T09:03:58.628] [ERROR] ma-core - delete Role :missing ID testing testing testing
[2021-12-06T09:03:58.639] [ERROR] ma-core - get All Role :missing property testing testing testing
[2021-12-06T09:03:58.641] [ERROR] ma-core - get All Role :missing property NaN post 1234
[2021-12-06T09:03:58.650] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2021-12-06T09:03:58.651] [ERROR] ma-core - get by id Role :role not found testing testing testing
[2021-12-06T09:03:58.653] [ERROR] ma-core - get by id Role :role not found NaN post 1234
[2021-12-06T09:03:58.665] [ERROR] ma-core - get by user Role :user not found testing testing testing
[2021-12-06T09:03:58.667] [ERROR] ma-core - get by user Role :role not found testing testing testing
[2021-12-06T09:03:58.669] [ERROR] ma-core - get by user Role :role not found NaN get 1234
[2021-12-06T09:03:58.672] [ERROR] ma-core - add Role :missing property testing testing testing
[2021-12-06T09:03:58.675] [ERROR] ma-core - add Role :missing property NaN post 1234
[2021-12-06T09:03:58.689] [ERROR] ma-core - update Role :role not found testing testing testing
[2021-12-06T09:03:58.690] [ERROR] ma-core - update Role :role not found testing testing testing
[2021-12-06T09:03:58.692] [ERROR] ma-core - update Role :role not found NaN post 1234
[2021-12-06T09:03:58.701] [ERROR] ma-core - add Client :missing property testing testing testing
[2021-12-06T09:03:58.702] [ERROR] ma-core - add Client :missing property NaN post 1234
[2021-12-06T09:03:58.727] [ERROR] ma-core - 
[2021-12-06T09:03:58.787] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2021-12-06T09:03:58.789] [ERROR] ma-core - delete Sla :sla not found testing testing testing
[2021-12-06T09:03:58.792] [ERROR] ma-core - delete Sla :sla not found NaN post 1234
[2021-12-06T09:03:58.800] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2021-12-06T09:03:58.802] [ERROR] ma-core - get sla By Id :sla not found testing testing testing
[2021-12-06T09:03:58.803] [ERROR] ma-core - get sla By Id :sla not found NaN post 1234
[2021-12-06T09:03:58.810] [ERROR] ma-core - Error occur while Getting Sla By slaContract Id : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/sla/getByslaContract/getslaBySlaContract.service.test.js:70:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.819] [ERROR] ma-core - add Sla :missing property testing testing testing
[2021-12-06T09:03:58.822] [ERROR] ma-core - add Sla :missing property NaN post 1234
[2021-12-06T09:03:58.838] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2021-12-06T09:03:58.839] [ERROR] ma-core - update sla By SlaContract :sla not found testing testing testing
[2021-12-06T09:03:58.840] [ERROR] ma-core - update sla By SlaContract :sla not found NaN post 1234
[2021-12-06T09:03:58.850] [ERROR] ma-core - delete SlaContract :slaContract not found testing testing testing
[2021-12-06T09:03:58.851] [ERROR] ma-core - delete SlaContract :slaContract not found NaN post 1234
[2021-12-06T09:03:58.863] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/slaContract/getAllSlaContractByCustomerId/getAllSlaContractByCustomerIdServiceTest.js:56:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:58.870] [ERROR] ma-core - get slaContract By Customer :customer not found testing testing testing
[2021-12-06T09:03:58.872] [ERROR] ma-core - get slaContract By Customer :customer not found NaN post 1234
[2021-12-06T09:03:58.877] [ERROR] ma-core - get slaContract By Id :slaContract not found testing testing testing
[2021-12-06T09:03:58.880] [ERROR] ma-core - get slaContract By Id :slaContract not found NaN post 1234
[2021-12-06T09:03:58.889] [ERROR] ma-core - add SlaContract :missing property testing testing testing
[2021-12-06T09:03:58.890] [ERROR] ma-core - add SlaContract :missing property NaN post 1234
[2021-12-06T09:03:58.900] [ERROR] ma-core - update slaContract By Customer :slaContract not found testing testing testing
[2021-12-06T09:03:58.902] [ERROR] ma-core - update slaContract By Customer :slaContract not found NaN post 1234
[2021-12-06T09:03:58.997] [ERROR] ma-core - Get by Customer Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getAllSystemByCustomerId/getAllSystemByCustomerIdServiceTest.js:50:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:59.018] [ERROR] ma-core - Get Categories by Customer ID and Type ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getCategoryByTypesByCustomer/getCategoryByTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:59.044] [ERROR] ma-core - Get types by Customer ID Error : Error: Random error
    at Context.<anonymous> (/home/azer/avaxia-monitpring-app/core-service/test/unit/system/getTypeByCustomer/getTypesByCustomerServiceTest.js:122:21)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:680:10)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:803:12
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:595:14)
    at /home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:605:7
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:488:14)
    at cbHookRun (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:553:7)
    at done (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:310:5)
    at callFn (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:389:7)
    at Hook.Runnable.run (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runnable.js:354:5)
    at next (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:512:10)
    at Immediate._onImmediate (/home/azer/avaxia-monitpring-app/core-service/node_modules/mocha/lib/runner.js:573:5)
    at processImmediate (internal/timers.js:464:21)
[2021-12-06T09:03:59.088] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2021-12-06T09:03:59.094] [ERROR] ma-core - get by id Task :task not found testing testing testing
[2021-12-06T09:03:59.095] [ERROR] ma-core - get by id Task :task not found NaN post 1234
[2021-12-06T09:03:59.102] [ERROR] ma-core - get All Task By filter error :error testing testing testing
[2021-12-06T09:03:59.224] [ERROR] ma-core - get Created Tasks error : error testing testing testing
[2021-12-06T09:03:59.230] [ERROR] ma-core - get Created Tasks error : error NaN post 1234
[2021-12-06T09:03:59.240] [ERROR] ma-core - add Task :missing property testing testing testing
[2021-12-06T09:03:59.242] [ERROR] ma-core - add Task :missing property NaN post 1234
[2021-12-06T09:03:59.255] [ERROR] ma-core - add Many Task :missing property testing testing testing
[2021-12-06T09:03:59.257] [ERROR] ma-core - add Many Task :missing property NaN post 1234
[2021-12-06T09:03:59.268] [ERROR] ma-core - update Task :task not found testing testing testing
[2021-12-06T09:03:59.270] [ERROR] ma-core - update Task :task not found NaN post 1234
[2021-12-06T09:03:59.278] [ERROR] ma-core - Update Task Assignee :task not found testing testing testing
[2021-12-06T09:03:59.292] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task testing testing testing
[2021-12-06T09:03:59.294] [ERROR] ma-core - Failed to Cancel the Task :failed to update the task NaN post 1234
[2021-12-06T09:03:59.302] [ERROR] ma-core - Failed to delete the Task :failed to update the task testing testing testing
[2021-12-06T09:03:59.303] [ERROR] ma-core - Failed to delete the Task :failed to update the task NaN post 1234
[2021-12-06T09:03:59.311] [ERROR] ma-core - Failed to finish the Task :failed to update the task testing testing testing
[2021-12-06T09:03:59.312] [ERROR] ma-core - Failed to finish the Task :failed to update the task NaN post 1234
[2021-12-06T09:03:59.320] [ERROR] ma-core - Failed to reject the Task :failed to update the task testing testing testing
[2021-12-06T09:03:59.321] [ERROR] ma-core - Failed to reject the Task :failed to update the task NaN post 1234
[2021-12-06T09:03:59.331] [ERROR] ma-core - Failed to validate the Task :failed to update the task testing testing testing
[2021-12-06T09:03:59.332] [ERROR] ma-core - Failed to validate the Task :failed to update the task NaN post 1234
[2021-12-06T09:03:59.346] [ERROR] ma-core - update Task :You are not authorized to perform this action testing testing testing
[2021-12-06T09:03:59.349] [ERROR] ma-core - update Task :task not found NaN post 1234
[2021-12-06T09:03:59.430] [ERROR] ma-core - random Error
[2021-12-06T09:04:00.093] [ERROR] ma-core - random error
[2021-12-06T09:06:31.925] [ERROR] ma-core - delete Result Form :task not found testing testing testing
[2021-12-06T09:06:31.928] [ERROR] ma-core - delete Result Form :task not found NaN post 1234
[2021-12-06T09:06:31.946] [ERROR] ma-core - get by id Result Form :task not found testing testing testing
[2021-12-06T09:06:31.949] [ERROR] ma-core - get by id Result Form :task not found NaN post 1234
[2021-12-06T09:06:31.958] [ERROR] ma-core - add result form :missing property testing testing testing
[2021-12-06T09:06:31.959] [ERROR] ma-core - add result form :missing property NaN post 1234
[2021-12-06T09:06:31.968] [ERROR] ma-core - update Result Form  :task not found testing testing testing
[2021-12-06T09:06:31.971] [ERROR] ma-core - update Result Form  :task not found NaN post 1234
